export const ACCEDER_ACCEDER_BEGIN = 'ACCEDER_ACCEDER_BEGIN';
export const ACCEDER_ACCEDER_SUCCESS = 'ACCEDER_ACCEDER_SUCCESS';
export const ACCEDER_ACCEDER_FAILURE = 'ACCEDER_ACCEDER_FAILURE';
export const ACCEDER_ACCEDER_DISMISS_ERROR = 'ACCEDER_ACCEDER_DISMISS_ERROR';
export const ACCEDER_LIMPIAR_USUARIO = 'ACCEDER_LIMPIAR_USUARIO';
