export const INFORMES_TRAER_COMISIONES_BEGIN = 'INFORMES_TRAER_COMISIONES_BEGIN';
export const INFORMES_TRAER_COMISIONES_SUCCESS = 'INFORMES_TRAER_COMISIONES_SUCCESS';
export const INFORMES_TRAER_COMISIONES_FAILURE = 'INFORMES_TRAER_COMISIONES_FAILURE';
export const INFORMES_TRAER_COMISIONES_DISMISS_ERROR = 'INFORMES_TRAER_COMISIONES_DISMISS_ERROR';
