export const SERVICIOS_TRAER_SERVICIO_BEGIN = 'SERVICIOS_TRAER_SERVICIO_BEGIN';
export const SERVICIOS_TRAER_SERVICIO_SUCCESS = 'SERVICIOS_TRAER_SERVICIO_SUCCESS';
export const SERVICIOS_TRAER_SERVICIO_FAILURE = 'SERVICIOS_TRAER_SERVICIO_FAILURE';
export const SERVICIOS_TRAER_SERVICIO_DISMISS_ERROR = 'SERVICIOS_TRAER_SERVICIO_DISMISS_ERROR';
