export const PERSONAS_TRAER_PERSONA_BEGIN = 'PERSONAS_TRAER_PERSONA_BEGIN';
export const PERSONAS_TRAER_PERSONA_SUCCESS = 'PERSONAS_TRAER_PERSONA_SUCCESS';
export const PERSONAS_TRAER_PERSONA_FAILURE = 'PERSONAS_TRAER_PERSONA_FAILURE';
export const PERSONAS_TRAER_PERSONA_DISMISS_ERROR = 'PERSONAS_TRAER_PERSONA_DISMISS_ERROR';
export const PERSONAS_LIMPIAR_PERSONA = 'PERSONAS_LIMPIAR_PERSONA';
