export const CONTACTO_LISTAR_BEGIN = 'CONTACTO_LISTAR_BEGIN';
export const CONTACTO_LISTAR_SUCCESS = 'CONTACTO_LISTAR_SUCCESS';
export const CONTACTO_LISTAR_FAILURE = 'CONTACTO_LISTAR_FAILURE';
export const CONTACTO_LISTAR_DISMISS_ERROR = 'CONTACTO_LISTAR_DISMISS_ERROR';
