export const USUARIOS_MI_USUARIO_BEGIN = 'USUARIOS_MI_USUARIO_BEGIN';
export const USUARIOS_MI_USUARIO_SUCCESS = 'USUARIOS_MI_USUARIO_SUCCESS';
export const USUARIOS_MI_USUARIO_FAILURE = 'USUARIOS_MI_USUARIO_FAILURE';
export const USUARIOS_MI_USUARIO_DISMISS_ERROR = 'USUARIOS_MI_USUARIO_DISMISS_ERROR';
