export const FLETES_TRAE_FLETES_BEGIN = 'FLETES_TRAE_FLETES_BEGIN';
export const FLETES_TRAE_FLETES_SUCCESS = 'FLETES_TRAE_FLETES_SUCCESS';
export const FLETES_TRAE_FLETES_FAILURE = 'FLETES_TRAE_FLETES_FAILURE';
export const FLETES_TRAE_FLETES_DISMISS_ERROR = 'FLETES_TRAE_FLETES_DISMISS_ERROR';
