export const SEGUROS_TRAE_SEGUROS_BEGIN = 'SEGUROS_TRAE_SEGUROS_BEGIN';
export const SEGUROS_TRAE_SEGUROS_SUCCESS = 'SEGUROS_TRAE_SEGUROS_SUCCESS';
export const SEGUROS_TRAE_SEGUROS_FAILURE = 'SEGUROS_TRAE_SEGUROS_FAILURE';
export const SEGUROS_TRAE_SEGUROS_DISMISS_ERROR = 'SEGUROS_TRAE_SEGUROS_DISMISS_ERROR';
